services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    mem_limit: 512m
  api:
    build:
      context: .
      target: develop
    ports:
      - 5219:5219
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5219
      - ConnectionStrings__NexiumConnection=Host=database;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
    mem_limit: 1024m
    depends_on:
      - database
  frontend:
    build:
      context: ../../Nexium-Frontend
    volumes:
      - ../../Nexium-Frontend/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    mem_limit: 3048m
    depends_on:
      - api
